version: '3.6'
services:
  efm:
    privileged: true
    container_name: efm
    image: efm
    build:
     context: .
     dockerfile: Dockerfile
    volumes:
      - <path_to_i2p_repo>:/workspace/i2p/
      - <path_to_i2p_repo>/models/vision/paella_adaptions:/workspace/i2p/Paella/utils
    entrypoint: zsh
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]